export const environment = {
  production: true,
  BACKEND_URL: '${BACKEND_URL}',
  FRONTEND_URL: '${FRONTEND_URL}',
  DJANGO_APP_CLIENT_ID: '${DJANGO_APP_CLIENT_ID}',
  DJANGO_APP_CLIENT_SECRET: '${DJANGO_APP_CLIENT_SECRET}',
  GOOGLE_API_KEY_CLIENT_ID: '${GOOGLE_API_KEY_CLIENT_ID}',
};