version: "3.9"

services:
  backend:
    container_name: backend
    build: 'einkaufsliste_backend/'
    command: >
      sh -c "python /code/manage.py collectstatic --no-input  && python /code/manage.py makemigrations && python /code/manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:80"
    volumes:
      - /static:/static
    depends_on:
      - db
    env_file:
      - prod_vars.env
  frontend:
    build: 'einkaufsliste_frontend/'
    ports:
      - 4200:80
    env_file:
      - prod_vars.env
  reverse_proxy:
    image: nginx:1.19.0
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/html:/var/www/html
      - /static:/static  # <-- needs testing
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - prod_vars.env
  
  prometheus:
    image: prom/prometheus
    restart: 'no'
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus-prod.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: 'no'
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

volumes:
  postgres_data:
  prometheus_data: {}
  grafana_data: {}