version: "3.9"

services:
  web:
    build: 'einkaufsliste_backend/'
    command: >
      sh -c "python /code/manage.py collectstatic --no-input  && python /code/manage.py makemigrations && python /code/manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:80"
    volumes:
      - /static:/static
    depends_on:
      - db
    env_file:
      - prod_vars.env
  frontend:
    build: 'einkaufsliste_frontend/'
    ports:
      - 4200:80
    env_file:
      - prod_vars.env
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - prod_vars.env
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.de"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"

volumes:
  postgres_data:
