# Generated by Django 4.1.2 on 2022-11-15 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppinglist', '0002_shoppinglist_owner_alter_shoppinglist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
