# Generated by Django 4.1.2 on 2022-11-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0004_alter_shoppinglist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
