# Generated by Django 4.1.2 on 2022-11-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0009_shoppinglistentry_delete_shoppinglistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistentry',
            name='status',
            field=models.CharField(choices=[('1', 'open'), ('2', 'closed'), ('3', 'in_progess')], default='1', max_length=20),
        ),
    ]
